### ISSUE TITLE
When an element has no attributes, `AttrDisplay` should say so

### ISSUE THREAD

**Issue by sean-fitzpatrick** [siefkenj/pretext-book#50]
For an element like `<c>` that has no attributes, writing `<AttrDisplay name="c" />` should produce a message that there are no attributes.

Similarly, if an element has no children (likely it contains only text; given as `xs:string` in the schema), instead of displaying nothing,  <ChildrenDisplay name="c" /> could produce a message like "Contains only text".

**Comment by siefkenj** [comment]
Should be fixed by #64
