### ISSUE TITLE
Contents of a <p>, categorized

### ISSUE THREAD

**Issue by sean-fitzpatrick** [siefkenj/pretext-book#70]
Here is my rough categorization of the contents of a `<p>`:

Characters	
nbsp	(non-breaking space)
mdash	(em-dash)
ndash	(en-dash)
lsq	(left single quote)
rsq	(right single quote)
rq	(right double quote)
lq	(left double quote)
ldblbracket	(left double bracket)
rdblbracket	(right double bracket)
langle	(left angle)
rangle	(right angle)
minus	(minus sign)
times	(multiplication sign)
solidus	(division slash)
obelus	(division symbol)
plusminus	(plus/minus sign)
degree	(degree symbol)
prime	(prime symbol)
dblprime	(double prime symbol)
ellipsis	
midpoint	(centred dot)
swungdash	(weird tilde thingy)
permille	  (percent, but 1000)
pilcrow	(paragraph mark)
section-mark	(section mark)
copyleft	  (backwards copyright)
copyright	
registered	
trademark	
phonomark	(like registered, but a P)
servicemark	(like trademark, but SM)

Text macros	
today	(prints the date)
timeofday	(prints the time)
tex	(TeX)
latex	(LaTeX)
xetex	(XeTeX)
xelatex	(XeLaTeX)
pretext	(PreTeXt)
webwork	(WeBWorK)
ad	(a.d. (anno domini))
am	(a.m. (ante meridian))
bc	(b.c. (before Christ))
ca	(ca. (circa))
eg	(e.g. (for example))
etal	(et. al.)
etc	(etc.)
ie	(i.e.)
nb	(n.b.)
pm	(p.m. (post meridian))
ps	(p.s. (post script))
vs	(vs.)
vis	(vis.)

Formatting environments
quantity   (for quantities with units)
abbr  (abbreviation)
acro  (acronym)
init  (initialization)
q  (quotes)
sq  (single quotes)
angles  (angle brackets)
dblbrackets  (double square brackets)
em  (emphasis)
term  (terminology -- bolded)
alert  (needs attentiion -- bolded)
pubtitle  (publication title)
articletitle  (article title)
foreign  (foreign language)
taxon  (taxonomy)
notation

Special 
icon  (allows for insertion of various symbols)
kbd  (keyboard icons)

Editing marks
delete
insert
stale

PTX tags
tag  (for entering a ptx tag)
tage  (self-closing tag)
attr  (attribute)

Music
doublesharp
sharp
natural
flat
doubleflat
scaledeg
timesignature
n
chord

Math
m
me
men
md
mdn

Lists
ol
ul
dl

Code
c
cd

Other
url  (external URL)
xref  (cross reference)
fn  (footnote)
idx  (index entry)
var  (WeBWorK variable)
fillin  (an answer blank, possibly deprecated)
email  (email address)

**Comment by sean-fitzpatrick** [comment]
Correction: `notation` should be under Other: it's like `idx`, but for notation.

**Comment by siefkenj** [comment]
Great! This has been incorporated into the new `<SyntaxDisplay />` so I am closing this issue.
